version: '3'

services:
  mongo:
    container_name: mongo-container
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=mongopass
      - MONGO_INITDB_DATABASE=authentication
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
      #   - ./mongo-certs:/etc/mongo-certs
      # command: mongod --tlsMode requireTLS --tlsCertificateKeyFile /etc/mongo-certs/mongodb.pem --tlsCAFile /etc/mongo-certs/mongodb-cert.crt

    networks:
      - three-tier-net

networks:
  three-tier-net:
    driver: bridge

volumes:
  mongo-data:
